// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';
//show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOIX-HNKe_hikHQ4j0DHQAYwjxngaXT6U',
    appId: '1:845708086002:android:9696cf8e49bad939021e6b',
    messagingSenderId: '845708086002',
    projectId: 'clinic-booking-app-a6f1b',
    storageBucket: 'clinic-booking-app-a6f1b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1XNIgjHWINV44521HXp6UfzeGfkVxug8',
    appId: '1:845708086002:web:6c44990caae15783021e6b',
    messagingSenderId: '845708086002',
    projectId: 'clinic-booking-app-a6f1b',
    authDomain: 'clinic-booking-app-a6f1b.firebaseapp.com',
    storageBucket: 'clinic-booking-app-a6f1b.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1XNIgjHWINV44521HXp6UfzeGfkVxug8',
    appId: '1:845708086002:web:6c44990caae15783021e6b',
    messagingSenderId: '845708086002',
    projectId: 'clinic-booking-app-a6f1b',
    authDomain: 'clinic-booking-app-a6f1b.firebaseapp.com',
    storageBucket: 'clinic-booking-app-a6f1b.firebasestorage.app',
  );
}
